modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config = "mekajadeupgrades_fixed.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="${meka_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="jade"
    type="required"
    versionRange="${jade_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism_extras"
    type="optional"
    versionRange="[1.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism_empowered_unleashed"
    type="optional"
    versionRange="[21.1-1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism_empowered"
    type="optional"
    versionRange="[0.0.0,)"
    ordering="NONE"
    side="BOTH"
